backend:
  name: github
  repo: Harriethw/queer-net # Path to your Github/Gitlab repository
  branch: main # Branch to update
  base_url: http://cms-test-640cec13ec4d.herokuapp.com # Path to ext auth provider
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "news"
            name: "news"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Link", name: "link", widget: "text", required: false }
              - {
                  label: "Thumbnail",
                  name: "thumbnail",
                  widget: "image",
                  required: false,
                }
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Hero Image", name: "image", widget: "image" }
      - label: "Resources"
        name: "resources"
        file: "content/resources.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Hero Image",
              name: "image",
              widget: "image",
              required: false,
            }
  - label: "Blog"
    name: "blog"
    folder: "_posts/blog"
    create: true
    slug: "{{title}}-{{year}}"
    identifier_field: name
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
